const papers = [
  {
    id: 1,
    title: "Track 1",
    description: "Cyber Security Resilience",
    topics: [
      "Machine Learning for Cyber Security",
      "Intrusion Detection Systems",
      "Intrusion Prevention Systems",
      "Firewall Evasion Detection Systems",
      "Firewall Optimization",
      "Incident Response",
      "Cyber Threat Intelligence",
    ],
  },
  {
    id: 2,
    title: "Track 2",
    description: "Cloud, Fod, and IoT Security",
    topics: [
      "Secure Data Transmission in Edge and Fog Environments",
      "Edge device Security",
      "Privacy-preserving techniques in IoT",
      "Trust Management in Cloud, Edge, and Fog",
      "Resilience and Reliability in Edge and Fog Networks",
      "Security for Serverless Computing at the Edge",
      "IoT Device Identity Management",
      "Edge and Fog IDS and IPS",
      "AAA for Edge and Fog Nodes",
      "Block Chain for Cloud, Edge and Fog",
    ],
  },
  {
    id: 3,
    title: "Track 3",
    description: "Data Mining and Knowledge Research",
    topics: [
      "Knowledge creation and Innovation",
      "Knowledge Management",
      "Semantic Web and Ontologies",
      "Knowledge Representation and Reasoning",
      "Cognitive Science and Knowledge Acquisition",
      "Data Mining and Knowledge Discovery",
      "Collaborative Knowledge Sharing",
      "Cross-Disciplinary Knowledge Integration",
    ],
  },
  {
    id: 4,
    title: "Track 4",
    description: "Cyber Security and Knowledge Research",
    topics: [
      "Threat Intelligence Knowledge Engineering",
      "Automated Security Decision Support Systems",
      "Security Knowledge Base Construction",
      "Building Datasets for Cyber Security Research",
      "Cyber Forensic Knowledge Engineering",
      "Security Analytics and Big Data Knowledge Engineering",
      "Human-Centric Cybersecurity Knowledge Engineering",
      "Distributed Cyber Security Knowledge Research towards efficient IDS/IPS/Anti-Malware systems",
    ],
  },
  {
    id: 5,
    title: "Track 5",
    description: "Cryptography, Application Security, SecDevOps",
    topics: [
      "Cryptography Research",
      "Application Security",
      "Web Application Security",
      "Continuous Integration/Continuous Deployment (CI/CD) Pipeline/Security",
      "Automated Security Testing",
      "Infrastructure as Code (IaC) Security",
      "Container Security",
      "Microservices Security",
      "Security Orchestration and Automation",
      "Security Monitoring and Logging",
      "Identity and Access Management (IAM) in DevOps",
      "Security Culture and Training",
    ],
  },
];

export default papers;